from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('signup', views.signup, name='signup'),
    path('signin', views.signin, name='signin'),
    path('', views.index, name='index'),
    path('<int:port_id>', views.irasas, name='irasas'),
    path('profilis/<str:username>', views.profilis, name='profilis'),
    path('manoprofilis/<str:pk>/redaguotiprofili', views.redaguotiprofili, name='redaguotiprofili'),
    path('manoprofilis/<str:pk>', views.manoprofilis, name='manoprofilis'),
    path('darboskelbimai', views.skelbimai, name='skelbimai'),
    path('darboskelbimai/<int:skelbimas_id>', views.skelbimas, name='skelbimas'),
    path('pridetiskelbima', views.pridetiskelbima, name='pridetiskelbima'),
    path('darboskelbimai/<int:skelb_id>/aplikavimas', views.aplikavimas, name='aplikavimas'),
    path('manoskelbimai/<str:pk>', views.manoskelbimai, name='manoskelbimai'),
    path('delete_skelbimas/<int:id>', views.delete_skelbimas, name='delete_skelbimas'),
    # path('del_comment/<int:id>', views.del_comment, name='del_comment'),
    path('edit_skelbimas/<int:id>', views.edit_skelbimas, name='edit_skelbimas'),
    path('inbox', views.inbox, name='inbox'),
    path('search_portfolio', views.search_portfolio, name='search_portfolio'),
    path('search_skelbimai', views.search_skelbimai, name='search_skelbimai'),
    path('new', views.user_search, name='user_search'),
    path('new/<username>', views.new_conversation, name='newconversation'),
    path('directs/<username>', views.directs, name='directs'),
    path('send', views.send_direct, name='send_direct'),
    path('like-post', views.like_post, name='like-post'),
    path('follow', views.follow, name='follow'),
    path('<int:port_id>/like', views.like, name='portlike'),
    path('<int:port_id>/favoriteportfolios', views.favorite_port, name='portfavorite'),
    path('darboskelbimai/<int:skelb_id>/favoriteskelbimai', views.favorite_skelb, name='skelbfavorite'),
    path('issaugoti', views.issaugoti, name='issaugoti'),
    path('notifications', views.show_notifications, name='show-notifications'),
    path('notifications/<int:noti_id>/delete', views.delete_notifications, name='delete-notification'),
    path('forget-password', views.ForgetPass, name="forget_password"),
    path('change-password/<token>/', views.ChangePass, name="change_password"),
    path('manoprofilis/<str:pk>/addirasa', views.addirasa, name='addirasa'),

]